name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build and push image
        run: |
          docker build -t hello-world-app .
          docker tag hello-world-app:latest 730335608948.dkr.ecr.us-east-1.amazonaws.com/hello-world-app:latest
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335608948.dkr.ecr.us-east-1.amazonaws.com
          docker push 730335608948.dkr.ecr.us-east-1.amazonaws.com/hello-world-app:latest
          

      - name: Update ECS task definition
        run: |
          aws ecs update-task-definition --family hello-world-task --requires-compatibilities FARGATE --network-mode awsvpc --cpu 1024 --memory 512 --execution-role-arn 730335608948:ecs-task-execution-role --container-definitions '[{"name": "hello-world-app", "image": "hello-world-app:latest", "portMappings": [{"containerPort": 3000, "hostPort": 3000}]}]'

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster hello-world-cluster --service hello-world-service --task-definition hello-world-task --desired-count 1
